### ISSUE TITLE
Z-index issues

### ISSUE THREAD

**Issue by gdaniel** [xatkit-bot-platform/xatkit-react#11]
The chatbox has a z-index of 1, that may be an issue in website using multiple z-index levels, as the bot may be behind other components.

Quick fix:
```css
.rcw-widget-container {
z-index: 10000 !important;
}
```
